---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drupal-mysql-pvc
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

      