---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: iron-gallery
  labels:
    name: iron-gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      run: iron-gallery
  template:
    metadata:
      labels:
        run: iron-gallery
    spec:
      containers:
        - image: kodekloud/irongallery:2.0
          name: iron-gallery
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "100Mi"
              cpu: 50m
          volumeMounts:
            - mountPath: /usr/share/nginx/html/data
              name: config
            - mountPath: /usr/share/nginx/html/uploads
              name: images
      volumes:
      - name: config
        emptyDir: {}
      - name: images
        emptyDir: {}

        